name: flutter_exif_rotation
description:
  Flutter plugin that fixes the picture orientation when it's took in landscape for some devices.
version: 0.2.7
author: Nadia Ghebreial Nieto <nadiagnieto@gmail.com>
homepage: https://github.com/NGhebreial/flutter_exif_rotation
repository: https://github.com/NGhebreial/flutter_exif_rotation

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.flutter.plugins.flutterexifrotation
    pluginClass: FlutterExifRotationPlugin
